### ISSUE TITLE
[docs] Search does not work when docs is built with Sphinx 6.1.3

### ISSUE THREAD

**Issue by alhambrav** [craftercms/craftercms#6010]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [X] The issue is in the latest released 3.1.x

### Describe the issue

After updating sphinx-build to 6.1.3, search does not seem to be working.  When you enter a search term, there is nothing displayed and there is an error in the console

```
Uncaught TypeError: $.getQueryParameters is not a function
    at Object.init (searchtools.js:75:24)
    at HTMLDocument.<anonymous> (searchtools.js:515:12)
    at e (jquery.js:2:30038)
    at t (jquery.js:2:30340)
```

Starting on sphinx-build 6.0.0, jquery.js was removed and is no longer automatically injected into themes.  In the [release notes](https://www.sphinx-doc.org/en/master/changes.html#release-6-0-0-released-dec-29-2022), they recommended to either use the [sphinxcontrib.jquery](https://github.com/sphinx-contrib/jquery/) extension or manually ensure jquery is added.

I tried using the sphinxcontrib.jquery extension instead of the jquery being copied over and the search still does not work but is exhibiting a different behavior than above and is described below:

I added the sphinxcontrib.jquery extension in the conf.py file
```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'edit_on_github',
    'sphinx.ext.extlinks',
    'version_tag',
    'sphinx_copybutton',
    'sphinxext.remoteliteralinclude',
    'sphinx_tabs.tabs',
    'sphinxcontrib.jquery'
]
```

Build the docs after adding the extension and do a search... Notice that it looks like it never finishes searching and when you look in the console you see the following error:

```
searchtools.js:169 Uncaught ReferenceError: $u is not defined
    at Object.query (searchtools.js:169:13)
    at Object.setIndex (searchtools.js:98:20)
    at <anonymous>:1:8
    at b (jquery.js:2:866)
    at Function.globalEval (jquery.js:2:2905)
    at text script (jquery.js:2:83080)
    at jquery.js:2:79470
    at l (jquery.js:2:79587)
    at XMLHttpRequest.<anonymous> (jquery.js:2:82355)
```

### Steps to reproduce

Steps:

1. Update sphinx-build to 6.1.3
2. Build the docs
3. Enter a search term on the search bar located at the top of the left sidebar
4. Notice there is nothing displayed and there is an error in the console.

### Screenshots and/or videos

![Screenshot 2023-04-11 at 11 41 49 AM](https://user-images.githubusercontent.com/25483966/231216435-41a794ae-529c-45a5-b3b9-6c6cf68dac2a.png)

Using the sphinxcontrib.jquery extension, this is how search looks like:
![Screenshot 2023-04-11 at 12 19 17 PM](https://user-images.githubusercontent.com/25483966/231227564-73484c8b-4302-4707-9a88-083d1a3b391e.png)

**Comment by sumerjabri** [comment]
Fixed.
